// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/best/ladr_spaces/ladr-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'E:/best/ladr_spaces/ladr-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import FileTextOutlined from 'E:/best/ladr_spaces/ladr-admin/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
export default { SmileOutlined, CrownOutlined, FileTextOutlined };
